# Generated by Django 5.2.6 on 2025-09-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='aws_face_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
